### ISSUE TITLE
Please add support for IPv6 in addition to IPv4

### ISSUE THREAD

**Issue by donwilson** [vovayatsyuk/sublime-ip-address#1]
I need quick access to both my IPv4 and IPv6 address if that's available. Thanks!

**Comment by vovayatsyuk** [comment]
Can you please check if any of these has your ipv6 address:

http://ipecho.net/plain
https://jsonip.com/

If so, can you insert the output here? (You may omit the ip)

**Comment by donwilson** [comment]
https://jsonip.com/ does have the ipv6 but it doesn't include my ipv4. Perhaps you could use this API - http://ip6only.me/ - at the bottom there's an API to return specifically ipv6 or ipv4 in a CSV format

**Comment by vovayatsyuk** [comment]
Thanks. Will try to add it.

Maybe these works for you too?

https://ipv4.jsonip.com/
https://ipv6.jsonip.com/

**Comment by donwilson** [comment]
Yep, those work as expected too

**Comment by vovayatsyuk** [comment]
Just added additional commands for ipv6 addresses.

Hope you'll like it!

**Comment by donwilson** [comment]
Perfect! Very thankful for the quick update
